### ISSUE TITLE
handle watch updates in the pacs and oscs

### ISSUE THREAD

**Issue by maverick-zhn** [trellisfw/trellisfw-broker#6]
There are some issues when using watches in the resources (pacs, oscs.) Revise the @oada/cerebral-module and @oada/oada-cache.

**Comment by maverick-zhn** [comment]
I got this error when using watches (this is in the cerebral-provider/build/index.js:44):
```
Uncaught TypeError: _this.context.controller.getSignal is not a function
    at http://localhost:3000/static/js/0.chunk.js:42545:39
    at Array.map (<anonymous>)
    at Provider.ProviderConstructor.get (http://localhost:3000/static/js/0.chunk.js:42544:35)
    at http://localhost:3000/static/js/0.chunk.js:42267:17
From previous event:
    at Object.push../node_modules/@oada/cerebral-module/sequences.js.get [as function] (http://localhost:3000/static/js/0.chunk.js:42250:29)
    at FunctionTreeExecution.runFunction (http://localhost:3000/static/js/0.chunk.js:84258:38)
    at http://localhost:3000/static/js/0.chunk.js:85843:19
    at FunctionTree._this.executeBranchWrapper (http://localhost:3000/static/js/0.chunk.js:84403:7)
    at runBranch (http://localhost:3000/static/js/0.chunk.js:85777:5)
    at http://localhost:3000/static/js/0.chunk.js:85810:9
    at FunctionTree._this.executeBranchWrapper (http://localhost:3000/static/js/0.chunk.js:84403:7)
    at runBranch (http://localhost:3000/static/js/0.chunk.js:85777:5)
    at runNextItem (http://localhost:3000/static/js/0.chunk.js:85779:9)
    at http://localhost:3000/static/js/0.chunk.js:85796:13
    at FunctionTreeExecution.runFunction (http://localhost:3000/static/js/0.chunk.js:84324:9)
    at http://localhost:3000/static/js/0.chunk.js:85843:19
    at FunctionTree._this.executeBranchWrapper (http://localhost:3000/static/js/0.chunk.js:84403:7)
    at runBranch (http://localhost:3000/static/js/0.chunk.js:85777:5)
    at http://localhost:3000/static/js/0.chunk.js:85810:9
    at FunctionTree._this.executeBranchWrapper (http://localhost:3000/static/js/0.chunk.js:84403:7)
    at runBranch (http://localhost:3000/static/js/0.chunk.js:85777:5)
    at runNextItem (http://localhost:3000/static/js/0.chunk.js:85779:9)
    at http://localhost:3000/static/js/0.chunk.js:85796:13
    at FunctionTreeExecution.runFunction (http://localhost:3000/static/js/0.chunk.js:84324:9)
    at http://localhost:3000/static/js/0.chunk.js:85843:19
    at FunctionTree._this.executeBranchWrapper (http://localhost:3000/static/js/0.chunk.js:84403:7)
    at runBranch (http://localhost:3000/static/js/0.chunk.js:85777:5)
    at runNextItem (http://localhost:3000/static/js/0.chunk.js:85779:9)
    at http://localhost:3000/static/js/0.chunk.js:85808:9
    at FunctionTree._this.executeBranchWrapper (http://localhost:3000/static/js/0.chunk.js:84403:7)
    at runBranch (http://localhost:3000/static/js/0.chunk.js:85777:5)
    at runNextItem (http://localhost:3000/static/js/0.chunk.js:85779:9)
    at http://localhost:3000/static/js/0.chunk.js:85796:13
    at FunctionTreeExecution.runFunction (http://localhost:3000/static/js/0.chunk.js:84324:9)
    at http://localhost:3000/static/js/0.chunk.js:85843:19
    at FunctionTree._this.executeBranchWrapper (http://localhost:3000/static/js/0.chunk.js:84403:7)
    at runBranch (http://localhost:3000/static/js/0.chunk.js:85777:5)
    at runNextItem (http://localhost:3000/static/js/0.chunk.js:85779:9)
    at http://localhost:3000/static/js/0.chunk.js:85796:13
    at FunctionTreeExecution.runFunction (http://localhost:3000/static/js/0.chunk.js:84324:9)
    at http://localhost:3000/static/js/0.chunk.js:85843:19
    at FunctionTree._this.executeBranchWrapper (http://localhost:3000/static/js/0.chunk.js:84403:7)
    at runBranch (http://localhost:3000/static/js/0.chunk.js:85777:5)
    at runNextItem (http://localhost:3000/static/js/0.chunk.js:85779:9)
    at http://localhost:3000/static/js/0.chunk.js:85808:9
    at FunctionTree._this.executeBranchWrapper (http://localhost:3000/static/js/0.chunk.js:84403:7)
    at runBranch (http://localhost:3000/static/js/0.chunk.js:85777:5)
    at runNextItem (http://localhost:3000/static/js/0.chunk.js:85779:9)
    at http://localhost:3000/static/js/0.chunk.js:85808:9
    at FunctionTree._this.executeBranchWrapper (http://localhost:3000/static/js/0.chunk.js:84403:7)
    at runBranch (http://localhost:3000/static/js/0.chunk.js:85777:5)
    at runNextItem (http://localhost:3000/static/js/0.chunk.js:85779:9)
    at http://localhost:3000/static/js/0.chunk.js:85796:13
    at FunctionTreeExecution.runFunction (http://localhost:3000/static/js/0.chunk.js:84324:9)
    at http://localhost:3000/static/js/0.chunk.js:85843:19
    at FunctionTree._this.executeBranchWrapper (http://localhost:3000/static/js/0.chunk.js:84403:7)
    at runBranch (http://localhost:3000/static/js/0.chunk.js:85777:5)
    at http://localhost:3000/static/js/0.chunk.js:85791:15
    at http://localhost:3000/static/js/0.chunk.js:84275:13
```
This is the piece of code generating the error (if starts at line 42):
```javascript
if (args.watch && args.watch.signals) {
    var sigs = args.watch.signals.map(function (signal) {
      return _this.context.controller.getSignal(signal);
    });

    args.watch.function = function (payload) {
      sigs.forEach(function (signal) {
        signal(payload);
      });
    };
  }
```

**Comment by maverick-zhn** [comment]
Debugging the code it turns out that the __this.context.controller._ does not contain a getSignal, instead, I used a getSequence and it worked. I am going to open an issue in the oada-provider

**Comment by maverick-zhn** [comment]
Fix the issue [`#1`](https://github.com/OADA/cerebral-provider/issues/1) in the https://github.com/OADA/cerebral-provider

**Comment by maverick-zhn** [comment]
After fixing the previous bug, this one appeared:
```
Error in oada.get TypeError: Cannot set property 'tree' of undefined
    at Object._callee12$ (index.js:573)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:290)
    at Generator.prototype.<computed> [as next] (runtime.js:116)
    at step (asyncToGenerator.js:21)
    at asyncToGenerator.js:32
```

**Comment by maverick-zhn** [comment]
Tomo fixed the error. Tomo published a new version of the **oada-cache** `v3.0.1` that fixed this error.

**Comment by maverick-zhn** [comment]
New issues appeared, probably related to **Cerebral 5.0** that I am using in the Trellis++ Broker.

**Comment by maverick-zhn** [comment]
Updated **@oada/cerebral-provider** and **@oada/cerebral-module** to include the newer version of **oada-cache** and some fixes.

**Comment by maverick-zhn** [comment]
Issue en **@oada/cerebral-module:**
```
-->Error in oada.get Error: Cerebral - The sequence "Connections.setConnection" with action "" has an error: Cannot read property '/bookmarks/osc' of undefined
    at throwError (utils.js:72)
    at Object.currentState.<computed> [as set] (Store.js:93)
    at sequences.js:201
```
