### ISSUE TITLE
Private Data - Dataset

### ISSUE THREAD

**Issue by maverick-zhn** [trellisfw/trellisfw-broker#7]
OSC needs a dataset that can be used to generate PACs. These datasets will be used by the C++ OSCs. Define the dataset in the OSC definitions repository. Include the dataset in the **trellisfw-broker**.

**Comment by maverick-zhn** [comment]
Some problems with the **oada-cache** when sending multiple requests:

```
websocket.js:81 Uncaught Error: Request failed with status code 412
    at WebSocket.socket.onmessage (http://localhost:3000/static/js/0.chunk.js:46896:23)
From previous event:
    at _http (http://localhost:3000/static/js/0.chunk.js:46938:14)
    at _callee7$ (http://localhost:3000/static/js/0.chunk.js:43339:22)
    at tryCatch (http://localhost:3000/static/js/0.chunk.js:55140:17)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/0.chunk.js:55367:22)
    at Generator.prototype.<computed> [as next] (http://localhost:3000/static/js/0.chunk.js:55193:21)
    at step (http://localhost:3000/static/js/0.chunk.js:51494:30)
    at http://localhost:3000/static/js/0.chunk.js:51512:14
    at new Promise (<anonymous>)
    at new F (http://localhost:3000/static/js/0.chunk.js:52273:22)
    at http://localhost:3000/static/js/0.chunk.js:51491:12
    at put (http://localhost:3000/static/js/0.chunk.js:43369:20)
    at handleRequest (http://localhost:3000/static/js/0.chunk.js:44236:16)
    at _callee4$ (http://localhost:3000/static/js/0.chunk.js:44606:51)
    at tryCatch (http://localhost:3000/static/js/0.chunk.js:55140:17)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/0.chunk.js:55367:22)
    at Generator.prototype.<computed> [as next] (http://localhost:3000/static/js/0.chunk.js:55193:21)
    at step (http://localhost:3000/static/js/0.chunk.js:51494:30)
    at http://localhost:3000/static/js/0.chunk.js:51512:14
    at new Promise (<anonymous>)
    at new F (http://localhost:3000/static/js/0.chunk.js:52273:22)
    at http://localhost:3000/static/js/0.chunk.js:51491:12
    at _sendRequest (http://localhost:3000/static/js/0.chunk.js:44635:22)
    at _callee21$ (http://localhost:3000/static/js/0.chunk.js:45526:52)
    at tryCatch (http://localhost:3000/static/js/0.chunk.js:55140:17)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/0.chunk.js:55367:22)
    at Generator.prototype.<computed> [as next] (http://localhost:3000/static/js/0.chunk.js:55193:21)
    at step (http://localhost:3000/static/js/0.chunk.js:51494:30)
    at http://localhost:3000/static/js/0.chunk.js:51505:13
```
